name: Trigger auto deployment for capps-riessiegpt2-webui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capps-riessiegpt2-webui-AutoDeployTrigger-661eb795-a42f-438e-9969-bf1f47f78fa3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAPPSRIESSIEGPT2WEBUI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPSRIESSIEGPT2WEBUI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPSRIESSIEGPT2WEBUI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: vscodedevdff093acry5kfkze4x3zdw.azurecr.io
          registryUsername: ${{ secrets.CAPPSRIESSIEGPT2WEBUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSRIESSIEGPT2WEBUI_REGISTRY_PASSWORD }}
          containerAppName: capps-riessiegpt2-webui
          resourceGroup: rg-jschoppink-6365
          imageToBuild: vscodedevdff093acry5kfkze4x3zdw.azurecr.io/capps-riessiegpt2-webui:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


